[package]
name = "sierradb-protocol"
version = "0.1.0" 
edition = "2024"
description = "Shared protocol types and utilities for SierraDB"

[dependencies]
# No external dependencies - pure Rust for maximum compatibility
